sudo: false
language: rust

before_install: |
    [ ${TRAVIS_BRANCH} = master ] &&
    [ ${TRAVIS_PULL_REQUEST} = false ] &&
    AUTHOR="$(git show --no-patch --format=format:%ae HEAD)" &&
    [ ${AUTHOR} != "cobalt@kstep.me" ]

script:
  - bash _deploy/deploy.sh

env:
  global:
    - ENC_LABEL: 962863eaefcf
