auto: false
pygments: false
markdown: kramdown

kramdown:
    use_coderay: false

title: Konstantin Stepanov
author:
    name: Konstantin Stepanov
    email: me@kstep.me
    github: kstep
    twitter: kstepme

