highlighter: none
markdown: kramdown
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

kramdown:
    enable_coderay: false

title: Konstantin Stepanov
author:
    name: Konstantin Stepanov
    email: me@kstep.me
    github: kstep
    twitter: kstepme

