#!/bin/sh

cd "$(dirname $0)/.."
rev=$(git rev-parse --short HEAD)

git rm -f manifest-*.appcache
cp _manifest.appcache.in manifest-$rev.appcache
sed -i -e '/^# VERSION/s#{{VERSION}}#'$rev'#' manifest-$rev.appcache
sed -i -e '/manifest/s#manifest="/manifest-[a-f0-9]\+.appcache"#manifest="/manifest-'$rev'.appcache"#' index.html
git add index.html manifest-$rev.appcache
git commit -m "Manifest file update"

